@startuml
participant Alice
participant Bob
Alice -> Bob: Authentication Request
alt successful case
Bob -> Alice: Authentication Accepted
else some kind of failure
Bob -> Alice: Authentication Failure
group My own label
Alice -> Log : Log attack start
loop 1000 times
alt successful case
Alice -> Bob: DNS Attack
else
Bob -> Alice: DNS Attack
end
end
Alice -> Log : Log attack end
end
== divider ==
else Another type of failure
Bob -> Alice: Please repeat
note left: note
end
@enduml
